version: "3.9"
services:
  books:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MURASHKIN_205"
      POSTGRES_USER: "MURASHKIN_205"
      POSTGRES_PASSWORD: "MURASHKIN_205"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/books.sql:/docker-entrypoint-initdb.d/books.sql
    ports:
      - "5501:5432"
      
  hospital:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MURASHKIN_205"
      POSTGRES_USER: "MURASHKIN_205"
      POSTGRES_PASSWORD: "MURASHKIN_205"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/hospital.sql:/docker-entrypoint-initdb.d/hospital.sql
    ports:
      - "5502:5432"
      
  railways:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MURASHKIN_205"
      POSTGRES_USER: "MURASHKIN_205"
      POSTGRES_PASSWORD: "MURASHKIN_205"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/railways.sql:/docker-entrypoint-initdb.d/railways.sql
    ports:
      - "5503:5432"